CREATE TABLE `dam_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dam_doc_type` enum('past_proposal','project_sheet','resume','certification','rfp','contract','boilerplate','other') NOT NULL DEFAULT 'other',
	`title` varchar(512) NOT NULL,
	`description` text,
	`dam_company_tag` enum('JPCL','Strans','Both'),
	`staffName` varchar(255),
	`staffId` int,
	`projectName` varchar(512),
	`projectNumber` varchar(128),
	`pursuitId` int,
	`proposalId` int,
	`clientName` varchar(512),
	`contractValue` varchar(64),
	`awardYear` int,
	`fileName` varchar(512) NOT NULL,
	`fileKey` text NOT NULL,
	`fileUrl` text NOT NULL,
	`mimeType` varchar(128),
	`fileSizeBytes` int,
	`extractedText` text,
	`extractedMeta` json,
	`dam_processing_status` enum('uploaded','processing','indexed','error') NOT NULL DEFAULT 'uploaded',
	`processingError` text,
	`tags` text,
	`uploadedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dam_documents_id` PRIMARY KEY(`id`)
);
